[package]
name = "source_dependency_tree"
version = "0.1.0"
edition = "2021"

[dependencies]
bindgen = { version = "0.70.1" }
clap = { version = "4.5.20", features = ["derive"] }
petgraph = { version = "0.6.5" }
petgraph-graphml = "3.1.0"
walkdir = { version = "2.5.0" }
