[package]
name = "source_dependency_tree"
version = "0.1.0"
edition = "2021"

[dependencies]
bindgen = { version = "0.70.1" }
clap = { version = "4.5.20", features = ["derive"] }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }
walkdir = { version = "2.5.0" }
